# Copyright (c) 2024-2025 Boston Dynamics AI Institute LLC. All rights reserved.

# This is an example that demonstrates configuration of the available controllers for a robot
# without an arm and without a namespace.
# It is not used!
# By default, a configuration matching this format that IS namespaced appropriately will be
# generated and used at launch time.

controller_manager:
  ros__parameters:
    update_rate: 333  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_state_controller:
      type: spot_controllers/ForwardStateController

    spot_joint_controller:
      type: spot_controllers/SpotJointController

    hardware_components_initial_state:
      unconfigured:
        - SpotSystem

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_sensor_frame"

forward_position_controller:
  ros__parameters:
    joints:
      - front_left_hip_x
      - front_left_hip_y
      - front_left_knee
      - front_right_hip_x
      - front_right_hip_y
      - front_right_knee
      - rear_left_hip_x
      - rear_left_hip_y
      - rear_left_knee
      - rear_right_hip_x
      - rear_right_hip_y
      - rear_right_knee
    interface_name: position

forward_state_controller:
  ros__parameters:
    joints:
      - front_left_hip_x
      - front_left_hip_y
      - front_left_knee
      - front_right_hip_x
      - front_right_hip_y
      - front_right_knee
      - rear_left_hip_x
      - rear_left_hip_y
      - rear_left_knee
      - rear_right_hip_x
      - rear_right_hip_y
      - rear_right_knee
    interface_names: 
      - position
      - velocity
      - effort

spot_joint_controller:
  ros__parameters:
    joints:
      - front_left_hip_x
      - front_left_hip_y
      - front_left_knee
      - front_right_hip_x
      - front_right_hip_y
      - front_right_knee
      - rear_left_hip_x
      - rear_left_hip_y
      - rear_left_knee
      - rear_right_hip_x
      - rear_right_hip_y
      - rear_right_knee
